### ISSUE TITLE
Are the tutorial videos still available? 

### ISSUE THREAD

**Issue by eugeneyan** [usaito/recsys2021-tutorial#1]
I'm trying to revisit this tutorial and recall having watched the videos for them. However, I can't seem to find them anymore and was wondering if the tutorial videos are still available online?

**Comment by usaito** [comment]
Hi, 

Thanks for your interest in our materials! 

Unfortunately, the video recording on the online conference platform seem available for only several months after the conference. We don't have the recording and are still waiting for the organizers to publicize it on the RecSys Youtube channel: https://www.youtube.com/channel/UC2nEn-yNA1BtdDNWziphPGA/playlists  Actually, we are also wondering when the recording will be publicity available.

**Comment by eugeneyan** [comment]
Thanks for responding. Yeap, I've checked the RecSys YouTube channel and couldn't find it. I guess we'll just have to wait then.

**Comment by usaito** [comment]
@eugeneyan 

Recording is now available on YouTube!

https://youtu.be/HMo9fQMVB4w

**Comment by eugeneyan** [comment]
@usaito that's great news! thanks for making it happen :bow:
