### ISSUE TITLE
hyperparameter tuning on real data

### ISSUE THREAD

**Issue by Chunpai** [usaito/recsys2021-tutorial#2]
Hello Yuta, 

Thank you for your terrific work on this tutorial. I have several questions on the hyperparameter tuning, and hope you could help me. 

1. I guess the parameter tau in SyntheticBanditDataset should be beta now. 
2. I think the synthetic data (including the pscore) is generated by using linear_behavior_policy. If we don't know the behavior policy except the logged bandit feedback, could we still be able to train the IPWLearner? 
3. I think the calc_ground_truth_policy_value function is still estimating the policy value of $\hat{\pi}_b$, am I right?

Thank you very much.

Best,
Chunpai

**Comment by usaito** [comment]
Hi Chunpai,

Thank you for the feedback.

1. that's correct, but that is the change made in `obp==0.5.2`. This repository works with `obp==0.5.1` as specified in https://github.com/usaito/recsys2021-tutorial/blob/main/pyproject.toml
2. Yes, you can estimate the propensity score first by estimating the actions from the context with some classification methods, then use the estimated pscore \hat{\pi}_b to train the IPWLearner.
3. Not necessarily. We can specify the policy of which we want to know the ground-truth performance (policy value) via the argument `action_dist`. In general, we want to know the ground-truth performance of \pi_e.

**Comment by Chunpai** [comment]
Got it. Thank you so much, Yuta.
